import type { Tenant, User, Role, RoleId, AuditEntry, InvitePending } from "./types";

// ========================================
// Tenants
// ========================================
export const tenants: Tenant[] = [
  {
    id: "t1",
    name: "IntegrateWise APAC",
    slug: "iw-apac",
    logo: "🌏",
    plan: "enterprise",
    region: "india",
    dataResidency: "Mumbai, India (ap-south-1)",
    maturityLevel: 2,
    memberCount: 12,
    integrationCount: 14,
    createdAt: "2025-06-15",
    status: "active",
    compliance: ["SOC 2", "ISO 27001", "GDPR"],
    owner: "Arun Kumar",
  },
  {
    id: "t2",
    name: "IntegrateWise Singapore",
    slug: "iw-sg",
    logo: "🇸🇬",
    plan: "professional",
    region: "singapore",
    dataResidency: "Singapore (ap-southeast-1)",
    maturityLevel: 1,
    memberCount: 6,
    integrationCount: 8,
    createdAt: "2025-09-01",
    status: "active",
    compliance: ["SOC 2", "PDPA"],
    owner: "Mei Lin Chen",
  },
  {
    id: "t3",
    name: "IntegrateWise Australia",
    slug: "iw-au",
    logo: "🇦🇺",
    plan: "professional",
    region: "australia",
    dataResidency: "Sydney, Australia (ap-southeast-2)",
    maturityLevel: 1,
    memberCount: 4,
    integrationCount: 5,
    createdAt: "2025-11-10",
    status: "active",
    compliance: ["SOC 2", "APPs"],
    owner: "James Mitchell",
  },
  {
    id: "t4",
    name: "IntegrateWise Demo",
    slug: "iw-demo",
    logo: "🧪",
    plan: "starter",
    region: "global",
    dataResidency: "US East (us-east-1)",
    maturityLevel: 0,
    memberCount: 2,
    integrationCount: 0,
    createdAt: "2026-01-20",
    status: "trial",
    compliance: [],
    owner: "Demo User",
  },
];

// ========================================
// Users
// ========================================
export const users: User[] = [
  {
    id: "u1",
    name: "Arun Kumar",
    email: "arun.kumar@integratewise.ai",
    initials: "AK",
    role: "super_admin",
    status: "active",
    department: "Engineering",
    timezone: "IST (UTC+5:30)",
    lastActive: "2 min ago",
    joinedAt: "2025-06-15",
    mfaEnabled: true,
    tenants: ["t1", "t2", "t3", "t4"],
    viewModes: { personal: true, work: true, business: true, cs: true },
    modules: { ops: true, website: true, marketing: true, sales: true },
  },
  {
    id: "u2",
    name: "Priya Sharma",
    email: "priya.sharma@integratewise.ai",
    initials: "PS",
    role: "ops_manager",
    status: "active",
    department: "Revenue Operations",
    timezone: "IST (UTC+5:30)",
    lastActive: "15 min ago",
    joinedAt: "2025-07-01",
    mfaEnabled: true,
    tenants: ["t1"],
    viewModes: { personal: true, work: true, business: true, cs: false },
    modules: { ops: true, website: false, marketing: true, sales: true },
  },
  {
    id: "u3",
    name: "Rajesh Menon",
    email: "rajesh.menon@integratewise.ai",
    initials: "RM",
    role: "analyst",
    status: "active",
    department: "Business Intelligence",
    timezone: "IST (UTC+5:30)",
    lastActive: "1h ago",
    joinedAt: "2025-08-15",
    mfaEnabled: false,
    tenants: ["t1"],
    viewModes: { personal: true, work: true, business: false, cs: false },
    modules: { ops: true, website: false, marketing: false, sales: false },
  },
  {
    id: "u4",
    name: "Anjali Patel",
    email: "anjali.patel@integratewise.ai",
    initials: "AP",
    role: "cs_lead",
    status: "active",
    department: "Customer Success",
    timezone: "IST (UTC+5:30)",
    lastActive: "30 min ago",
    joinedAt: "2025-07-20",
    mfaEnabled: true,
    tenants: ["t1", "t2"],
    viewModes: { personal: true, work: true, business: true, cs: true },
    modules: { ops: true, website: false, marketing: false, sales: true },
  },
  {
    id: "u5",
    name: "Vikram Rao",
    email: "vikram.rao@integratewise.ai",
    initials: "VR",
    role: "sales_rep",
    status: "active",
    department: "Sales",
    timezone: "IST (UTC+5:30)",
    lastActive: "45 min ago",
    joinedAt: "2025-09-01",
    mfaEnabled: false,
    tenants: ["t1"],
    viewModes: { personal: true, work: true, business: false, cs: false },
    modules: { ops: false, website: false, marketing: false, sales: true },
  },
  {
    id: "u6",
    name: "Mei Lin Chen",
    email: "meilin.chen@integratewise.ai",
    initials: "MC",
    role: "admin",
    status: "active",
    department: "Operations",
    timezone: "SGT (UTC+8)",
    lastActive: "3h ago",
    joinedAt: "2025-09-01",
    mfaEnabled: true,
    tenants: ["t2"],
    viewModes: { personal: true, work: true, business: true, cs: true },
    modules: { ops: true, website: true, marketing: true, sales: true },
  },
  {
    id: "u7",
    name: "James Mitchell",
    email: "james.mitchell@integratewise.ai",
    initials: "JM",
    role: "admin",
    status: "active",
    department: "Operations",
    timezone: "AEST (UTC+11)",
    lastActive: "5h ago",
    joinedAt: "2025-11-10",
    mfaEnabled: true,
    tenants: ["t3"],
    viewModes: { personal: true, work: true, business: true, cs: true },
    modules: { ops: true, website: true, marketing: true, sales: true },
  },
  {
    id: "u8",
    name: "Deepak Joshi",
    email: "deepak.joshi@integratewise.ai",
    initials: "DJ",
    role: "marketing_mgr",
    status: "active",
    department: "Marketing",
    timezone: "IST (UTC+5:30)",
    lastActive: "2h ago",
    joinedAt: "2025-10-01",
    mfaEnabled: false,
    tenants: ["t1"],
    viewModes: { personal: true, work: true, business: false, cs: false },
    modules: { ops: false, website: true, marketing: true, sales: false },
  },
  {
    id: "u9",
    name: "Sarah Wong",
    email: "sarah.wong@partner.com",
    initials: "SW",
    role: "external_auditor",
    status: "active",
    department: "External - Audit",
    timezone: "SGT (UTC+8)",
    lastActive: "2d ago",
    joinedAt: "2026-01-05",
    mfaEnabled: true,
    tenants: ["t1", "t2"],
    viewModes: { personal: false, work: false, business: true, cs: false },
    modules: { ops: true, website: false, marketing: false, sales: false },
  },
  {
    id: "u10",
    name: "Karthik Nair",
    email: "karthik.nair@integratewise.ai",
    initials: "KN",
    role: "viewer",
    status: "invited",
    department: "Finance",
    timezone: "IST (UTC+5:30)",
    lastActive: "Never",
    joinedAt: "2026-02-05",
    mfaEnabled: false,
    tenants: ["t1"],
    viewModes: { personal: true, work: false, business: false, cs: false },
    modules: { ops: true, website: false, marketing: false, sales: false },
  },
  {
    id: "u11",
    name: "Nina Das",
    email: "nina.das@integratewise.ai",
    initials: "ND",
    role: "viewer",
    status: "suspended",
    department: "Sales",
    timezone: "IST (UTC+5:30)",
    lastActive: "30d ago",
    joinedAt: "2025-08-01",
    mfaEnabled: false,
    tenants: ["t1"],
    viewModes: { personal: false, work: false, business: false, cs: false },
    modules: { ops: false, website: false, marketing: false, sales: false },
  },
];

// ========================================
// Roles
// ========================================
export const roles: Role[] = [
  {
    id: "super_admin",
    name: "Super Admin",
    description: "Full platform access across all tenants. Can manage tenants, billing, and BYOM.",
    color: "#F44336",
    isSystem: true,
    userCount: 1,
    maxMaturityAccess: 5,
    permissions: {
      business_ops: { view: true, create: true, edit: true, delete: true, admin: true },
      website: { view: true, create: true, edit: true, delete: true, admin: true },
      marketing: { view: true, create: true, edit: true, delete: true, admin: true },
      sales: { view: true, create: true, edit: true, delete: true, admin: true },
      admin: { view: true, create: true, edit: true, delete: true, admin: true },
      intelligence_overlay: "full",
      integrations_manage: true,
      workflows_create: true,
      workflows_execute: true,
      agents_configure: true,
      byom_manage: true,
      export_data: true,
      bulk_actions: true,
      api_access: true,
      webhook_manage: true,
    },
    fieldAccess: { revenue_fields: "full", contact_pii: "full", api_keys: "full", audit_logs: "full", billing_info: "full" },
  },
  {
    id: "admin",
    name: "Admin",
    description: "Full access within assigned tenant. Can manage users, roles, integrations.",
    color: "#FF9800",
    isSystem: true,
    userCount: 2,
    maxMaturityAccess: 4,
    permissions: {
      business_ops: { view: true, create: true, edit: true, delete: true, admin: true },
      website: { view: true, create: true, edit: true, delete: true, admin: true },
      marketing: { view: true, create: true, edit: true, delete: true, admin: true },
      sales: { view: true, create: true, edit: true, delete: true, admin: true },
      admin: { view: true, create: true, edit: true, delete: false, admin: false },
      intelligence_overlay: "full",
      integrations_manage: true,
      workflows_create: true,
      workflows_execute: true,
      agents_configure: true,
      byom_manage: false,
      export_data: true,
      bulk_actions: true,
      api_access: true,
      webhook_manage: true,
    },
    fieldAccess: { revenue_fields: "full", contact_pii: "full", api_keys: "masked", audit_logs: "full", billing_info: "masked" },
  },
  {
    id: "ops_manager",
    name: "Ops Manager",
    description: "Manages business operations, integrations, and workflows within assigned modules.",
    color: "#0066FF",
    isSystem: true,
    userCount: 1,
    maxMaturityAccess: 3,
    permissions: {
      business_ops: { view: true, create: true, edit: true, delete: false, admin: false },
      website: { view: false, create: false, edit: false, delete: false, admin: false },
      marketing: { view: true, create: true, edit: true, delete: false, admin: false },
      sales: { view: true, create: true, edit: true, delete: false, admin: false },
      admin: { view: true, create: false, edit: false, delete: false, admin: false },
      intelligence_overlay: "full",
      integrations_manage: true,
      workflows_create: true,
      workflows_execute: true,
      agents_configure: false,
      byom_manage: false,
      export_data: true,
      bulk_actions: true,
      api_access: false,
      webhook_manage: false,
    },
    fieldAccess: { revenue_fields: "full", contact_pii: "full", api_keys: "hidden", audit_logs: "read", billing_info: "masked" },
  },
  {
    id: "analyst",
    name: "Analyst",
    description: "Read-only access to data and analytics. Can export reports.",
    color: "#7C4DFF",
    isSystem: true,
    userCount: 1,
    maxMaturityAccess: 2,
    permissions: {
      business_ops: { view: true, create: false, edit: false, delete: false, admin: false },
      website: { view: false, create: false, edit: false, delete: false, admin: false },
      marketing: { view: false, create: false, edit: false, delete: false, admin: false },
      sales: { view: false, create: false, edit: false, delete: false, admin: false },
      admin: { view: false, create: false, edit: false, delete: false, admin: false },
      intelligence_overlay: "read",
      integrations_manage: false,
      workflows_create: false,
      workflows_execute: false,
      agents_configure: false,
      byom_manage: false,
      export_data: true,
      bulk_actions: false,
      api_access: false,
      webhook_manage: false,
    },
    fieldAccess: { revenue_fields: "full", contact_pii: "masked", api_keys: "hidden", audit_logs: "read", billing_info: "hidden" },
  },
  {
    id: "cs_lead",
    name: "CS Lead",
    description: "Customer Success lead with full contact/account access and CS Intelligence view.",
    color: "#00C853",
    isSystem: true,
    userCount: 1,
    maxMaturityAccess: 3,
    permissions: {
      business_ops: { view: true, create: true, edit: true, delete: false, admin: false },
      website: { view: false, create: false, edit: false, delete: false, admin: false },
      marketing: { view: false, create: false, edit: false, delete: false, admin: false },
      sales: { view: true, create: false, edit: true, delete: false, admin: false },
      admin: { view: false, create: false, edit: false, delete: false, admin: false },
      intelligence_overlay: "full",
      integrations_manage: false,
      workflows_create: false,
      workflows_execute: true,
      agents_configure: false,
      byom_manage: false,
      export_data: true,
      bulk_actions: false,
      api_access: false,
      webhook_manage: false,
    },
    fieldAccess: { revenue_fields: "masked", contact_pii: "full", api_keys: "hidden", audit_logs: "hidden", billing_info: "hidden" },
  },
  {
    id: "sales_rep",
    name: "Sales Rep",
    description: "Sales team member with pipeline, deal, and contact access.",
    color: "#00C853",
    isSystem: true,
    userCount: 1,
    maxMaturityAccess: 2,
    permissions: {
      business_ops: { view: false, create: false, edit: false, delete: false, admin: false },
      website: { view: false, create: false, edit: false, delete: false, admin: false },
      marketing: { view: false, create: false, edit: false, delete: false, admin: false },
      sales: { view: true, create: true, edit: true, delete: false, admin: false },
      admin: { view: false, create: false, edit: false, delete: false, admin: false },
      intelligence_overlay: "read",
      integrations_manage: false,
      workflows_create: false,
      workflows_execute: false,
      agents_configure: false,
      byom_manage: false,
      export_data: false,
      bulk_actions: false,
      api_access: false,
      webhook_manage: false,
    },
    fieldAccess: { revenue_fields: "full", contact_pii: "full", api_keys: "hidden", audit_logs: "hidden", billing_info: "hidden" },
  },
  {
    id: "marketing_mgr",
    name: "Marketing Manager",
    description: "Marketing team lead with campaign, email, social, and website access.",
    color: "#FF4081",
    isSystem: true,
    userCount: 1,
    maxMaturityAccess: 2,
    permissions: {
      business_ops: { view: false, create: false, edit: false, delete: false, admin: false },
      website: { view: true, create: true, edit: true, delete: false, admin: false },
      marketing: { view: true, create: true, edit: true, delete: true, admin: true },
      sales: { view: false, create: false, edit: false, delete: false, admin: false },
      admin: { view: false, create: false, edit: false, delete: false, admin: false },
      intelligence_overlay: "read",
      integrations_manage: false,
      workflows_create: true,
      workflows_execute: true,
      agents_configure: false,
      byom_manage: false,
      export_data: true,
      bulk_actions: true,
      api_access: false,
      webhook_manage: false,
    },
    fieldAccess: { revenue_fields: "hidden", contact_pii: "masked", api_keys: "hidden", audit_logs: "hidden", billing_info: "hidden" },
  },
  {
    id: "viewer",
    name: "Viewer",
    description: "Read-only access to permitted modules. No edit, create, or delete capabilities.",
    color: "#9E9E9E",
    isSystem: true,
    userCount: 2,
    maxMaturityAccess: 1,
    permissions: {
      business_ops: { view: true, create: false, edit: false, delete: false, admin: false },
      website: { view: false, create: false, edit: false, delete: false, admin: false },
      marketing: { view: false, create: false, edit: false, delete: false, admin: false },
      sales: { view: false, create: false, edit: false, delete: false, admin: false },
      admin: { view: false, create: false, edit: false, delete: false, admin: false },
      intelligence_overlay: "none",
      integrations_manage: false,
      workflows_create: false,
      workflows_execute: false,
      agents_configure: false,
      byom_manage: false,
      export_data: false,
      bulk_actions: false,
      api_access: false,
      webhook_manage: false,
    },
    fieldAccess: { revenue_fields: "hidden", contact_pii: "hidden", api_keys: "hidden", audit_logs: "hidden", billing_info: "hidden" },
  },
  {
    id: "external_auditor",
    name: "External Auditor",
    description: "Read-only access to audit logs, compliance data, and business mode only. No PII access.",
    color: "#795548",
    isSystem: true,
    userCount: 1,
    maxMaturityAccess: 0,
    permissions: {
      business_ops: { view: true, create: false, edit: false, delete: false, admin: false },
      website: { view: false, create: false, edit: false, delete: false, admin: false },
      marketing: { view: false, create: false, edit: false, delete: false, admin: false },
      sales: { view: false, create: false, edit: false, delete: false, admin: false },
      admin: { view: true, create: false, edit: false, delete: false, admin: false },
      intelligence_overlay: "none",
      integrations_manage: false,
      workflows_create: false,
      workflows_execute: false,
      agents_configure: false,
      byom_manage: false,
      export_data: true,
      bulk_actions: false,
      api_access: false,
      webhook_manage: false,
    },
    fieldAccess: { revenue_fields: "masked", contact_pii: "hidden", api_keys: "hidden", audit_logs: "full", billing_info: "hidden" },
  },
];

// ========================================
// Audit Trail
// ========================================
export const auditEntries: AuditEntry[] = [
  { id: "a1", timestamp: "2026-02-09 14:32:05 IST", user: "Arun Kumar", action: "login", target: "Platform", details: "SSO login via Google", ipAddress: "103.21.xxx.xxx", tenant: "iw-apac", severity: "info" },
  { id: "a2", timestamp: "2026-02-09 14:28:00 IST", user: "Priya Sharma", action: "role_changed", target: "Vikram Rao", details: "Changed from Viewer to Sales Rep", ipAddress: "103.21.xxx.xxx", tenant: "iw-apac", severity: "warning" },
  { id: "a3", timestamp: "2026-02-09 13:45:12 IST", user: "Arun Kumar", action: "permission_changed", target: "Analyst Role", details: "Enabled export_data permission", ipAddress: "103.21.xxx.xxx", tenant: "iw-apac", severity: "warning" },
  { id: "a4", timestamp: "2026-02-09 12:10:00 IST", user: "Mei Lin Chen", action: "invite_sent", target: "partner@audit.com", details: "Invited as External Auditor to iw-sg", ipAddress: "52.77.xxx.xxx", tenant: "iw-sg", severity: "info" },
  { id: "a5", timestamp: "2026-02-09 11:30:22 IST", user: "Rajesh Menon", action: "exported", target: "Q4 Revenue Report", details: "Exported 1,247 records as CSV", ipAddress: "103.21.xxx.xxx", tenant: "iw-apac", severity: "info" },
  { id: "a6", timestamp: "2026-02-09 10:15:00 IST", user: "System", action: "mfa_toggled", target: "Rajesh Menon", details: "MFA reminder sent - not enabled", ipAddress: "—", tenant: "iw-apac", severity: "warning" },
  { id: "a7", timestamp: "2026-02-08 18:00:00 IST", user: "Arun Kumar", action: "tenant_switched", target: "iw-sg", details: "Switched from iw-apac to iw-sg", ipAddress: "103.21.xxx.xxx", tenant: "iw-apac", severity: "info" },
  { id: "a8", timestamp: "2026-02-08 16:45:33 IST", user: "Sarah Wong", action: "accessed", target: "Audit Logs", details: "Viewed full audit trail for iw-apac", ipAddress: "52.77.xxx.xxx", tenant: "iw-apac", severity: "info" },
  { id: "a9", timestamp: "2026-02-08 14:20:00 IST", user: "Arun Kumar", action: "created", target: "Nina Das", details: "Suspended user - policy violation", ipAddress: "103.21.xxx.xxx", tenant: "iw-apac", severity: "critical" },
  { id: "a10", timestamp: "2026-02-08 11:00:00 IST", user: "Deepak Joshi", action: "accessed", target: "Marketing Dashboard", details: "Viewed campaign performance data", ipAddress: "103.21.xxx.xxx", tenant: "iw-apac", severity: "info" },
  { id: "a11", timestamp: "2026-02-07 09:30:00 IST", user: "System", action: "permission_changed", target: "All Roles", details: "Compliance auto-review: no changes needed", ipAddress: "—", tenant: "iw-apac", severity: "info" },
  { id: "a12", timestamp: "2026-02-06 15:20:00 IST", user: "Anjali Patel", action: "exported", target: "Customer Health Report", details: "Exported 45 account records", ipAddress: "103.21.xxx.xxx", tenant: "iw-apac", severity: "info" },
];

// ========================================
// Pending Invites
// ========================================
export const pendingInvites: InvitePending[] = [
  { id: "inv1", email: "karthik.nair@integratewise.ai", role: "viewer", invitedBy: "Arun Kumar", sentAt: "2026-02-05", expiresAt: "2026-02-12", status: "pending" },
  { id: "inv2", email: "new.hire@integratewise.ai", role: "analyst", invitedBy: "Priya Sharma", sentAt: "2026-02-08", expiresAt: "2026-02-15", status: "pending" },
  { id: "inv3", email: "old.invite@partner.com", role: "external_auditor", invitedBy: "Arun Kumar", sentAt: "2026-01-15", expiresAt: "2026-01-22", status: "expired" },
];
