/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hrrbciljsqxnmuwwnrnt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhycmJjaWxqc3F4bm11d3ducm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2Mzc0MjUsImV4cCI6MjA4NTIxMzQyNX0.Af158eQ6-KoS-zlKslALN0SiprqkVFeId4iaV2sOXuY"